<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-R0QK2O8" ignored="0" name="Default test" tests="5" failures="1" timestamp="16 Dec 2018 17:37:25 GMT" time="0.131" errors="0">
  <testcase name="testcase1" time="0.008" classname="day8.BasicTesting"/>
  <testcase name="testcase7" time="0.004" classname="day8.BasicTesting">
    <failure type="org.testng.TestException" message="
Method BasicTesting.testcase7()[pri:0, instance:day8.BasicTesting@215be6bb] should have thrown an exception of type class java.lang.ArrayIndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method BasicTesting.testcase7()[pri:0, instance:day8.BasicTesting@215be6bb] should have thrown an exception of type class java.lang.ArrayIndexOutOfBoundsException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1416)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:695)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- testcase7 -->
  <testcase name="testcase4" time="0.011" classname="day8.BasicTesting"/>
  <testcase name="testcase2" time="0.003" classname="day8.BasicTesting"/>
  <testcase name="testcase3" time="0.004" classname="day8.BasicTesting"/>
</testsuite> <!-- Default test -->
